// ConflictError exception
import { AppError } from './AppError';

export class ConflictError extends AppError {
  constructor(message: string = 'Resource already exists') {
    super(message, 409);
  }
}
